# Generated by Django 5.2.9 on 2025-12-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["user", "created_at"], name="analytics_b_user_id_43c160_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["created_at"], name="analytics_b_created_812a0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="view",
            index=models.Index(
                fields=["blog", "timestamp"], name="analytics_v_blog_id_879865_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="view",
            index=models.Index(
                fields=["timestamp"], name="analytics_v_timesta_fe8125_idx"
            ),
        ),
    ]
